name: Build

on:
    push:
        branches: master
        tags: "**"

jobs:
    build:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - uses: actions/checkout@v4

            - name: Get Tag
              run: echo "TAG=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: maven
                  cache-dependency-path: "pom.xml"

            - name: Build with Maven
              run: mvn package -f pom.xml

            - name: Rename exe File
              run: mv target/Minecraft_Server_Manager.exe target/Minecraft_Server_Manager_${{env.TAG}}.exe

            - name: Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{secrets.ACTIONS_TOKEN}}
              with:
                  files: target/Minecraft_Server_Manager_${{env.TAG}}.exe
