name: Build

on:
    push:
        branches: master
        tags: "**"

jobs:
    build:
        runs-on: ubuntu-latest
        if: startsWith(github.ref, 'refs/tags/')
        steps:
            - uses: actions/checkout@v4

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: maven
                  cache-dependency-path: "pom.xml"

            - name: Build with Maven
              run: mvn package -f pom.xml

            - name: Release
              uses: softprops/action-gh-release@v2
              env:
                  GITHUB_TOKEN: ${{env.GITHUB_TOKEN}}
              with:
                  files: target/Minecraft_Server_Manager_v1.5.exe
